version: "3.9"

services:
  klinik_gigi:
    container_name: klinik_gigi
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3001:8001
    depends_on:
      - mysql_db
      - redis_db
    networks:
      - klinik-gigi-network

  mysql_db:
    container_name: mysql_db
    image: mysql:lts
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - klinik-gigi-network

  redis_db:
    container_name: redis_db
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - klinik-gigi-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql_db
    depends_on:
      - mysql_db
    networks:
      - klinik-gigi-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on:
      - klinik_gigi
    networks:
      - klinik-gigi-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email drgariesta26@gmail.com --agree-tos --no-eff-email
      -d klinikgigidrgariesta.online"
    networks:
      - klinik-gigi-network

volumes:
  mysql_data:

networks:
  klinik-gigi-network:
    external: true
