version: "3.9"

services:
  klinik_gigi:
    container_name: klinik_gigi
    build: ./docker
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:8001
    depends_on:
      - mysql_db
      - redis_db

  mysql_db:
    container_name: mysql_db
    image: mysql:lts
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis_db:
    container_name: redis_db
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql_db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql_db

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:

networks:
  klinik-gigi-network:
    external: true
