version: "3.9"

services:
  klinik_gigi:
    build: ./docker
    env_file:
      - .env
    ports:
      - 3000:8001
    depends_on:
      - mysql_db
      - redis_db

  mysql_db:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis_db:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:
